export const committees = [
  {
    img: "/img/Committees/UNHRC.png",
    shortName: "UNHRC",
    name: "United Nations Human Rights Council",
    description: "Discussion on the protection of refugees and internally displaced people from war crimes and crimes against humanity.",
    guide: "/",
    person1: "Mr. Dhruv Jain",
    person1_designation: "President",
    person1_img: "/img/CommitteePanel/Dhruv_Jain_UNHRC.jpg",
    person2: "Mr. Rohan Nagpal",
    person2_designation: "Research Associate",
    person2_img: "/img/CommitteePanel/Rohan_Nagpal_UNHRC(RA).jpg",
  },
  {
    img: "/img/Committees/UNCSW.png",
    shortName: "UNCSW",
    name: "United Nations Commission On The Status Of Women",
    description: "Impact of armed conflict on women with special emphasis on security of religious minorities in conflict and post conflict regions.",
    guide: "/",
    person1: "Ms. Kaveri Rawal",
    person1_designation: "Chairperson",
    person1_img: "/img/CommitteePanel/Kaveri_Rawal_UNCSW.jpg",
    person2: "Ms. Kashish Gumber",
    person2_designation: "Research Associate",
    person2_img: "/img/CommitteePanel/kashish_gumber_UNCSW.jpg",
  },
  {
    img: "/img/Committees/UNGA.png",
    shortName: "UNGA",
    name: "United Nations General Assembly",
    description: "Deliberation on the Israel Palestine conflict.",
    guide: "/",
    person1: "Mr. Ishaan Jain",
    person1_designation: "President",
    person1_img: "/img/CommitteePanel/Ishaan_Jain_UNGA.jpeg",
    person2: "Mr. Pranav Vinayak Jain",
    person2_designation: "Vice President",
    person2_img: "/img/CommitteePanel/Pranav_vinayak_jain_UNGA.jpg",
  },
  {
    img: "/img/Committees/UNOPS.png",
    shortName: "UNOPS",
    name: "United Nations Office For Project Services",
    description: "Reviewing the working of the Office of Project Services with emphasis on increasing accountability and transparency in operations.",
    guide: "/",
    person1: "Mr. Pratham Sharma",
    person1_designation: "Executive Director",
    person1_img: "/img/CommitteePanel/Pratham_Sharma_UNOPS.jpg",
    person2: "Mr. Vedansh Arora",
    person2_designation: "Deputy Executive Director",
    person2_img: "/img/CommitteePanel/Vedansh_Arora_UNHRC.png",
  },
  {
    img: "/img/Committees/3ARC.png",
    shortName: "ARC (Third Report)",
    name: "Administrative Reforms Commission (Third Report)",
    description: "Addressing and Combating Corruption in Government and Public Administration.",
    guide: "/",
    person1: "Mr. Rahul Menon",
    person1_designation: "Chairperson",
    person1_img: "/img/CommitteePanel/Rahul_Menon_ARC.jpg",
    person2: "Ms. Maaheen Faisal",
    person2_designation: "Member Secretary",
    person2_img: "/img/CommitteePanel/Maheen_Faisal_ARC.jpg",
  },
  {
    img: "/img/Committees/AIPPM.png",
    shortName: "AIPPM",
    name: "All India Political Parties Meet",
    description: "Discussing Electoral Reforms with special emphasis on political donations & submission of false affidavits by candidates.",
    guide: "/",
    person1: "Mr. Akshat Mohan Awasthi",
    person1_designation: "Moderator",
    person1_img: "/img/CommitteePanel/Akshat_M._Awasthy_AIPPM.jpg",
    person2: "Mr. Aditya Sharma",
    person2_designation: "Deputy Moderator",
    person2_img: "/img/CommitteePanel/Aditya_Sharma_AIPPM.JPG",
  },
  {
    img: "/img/Committees/ip.jpg",
    shortName: "IP",
    name: "International Press",
    description: "Agenda Comming Soon",
    guide: "/",
    person1: "Ms. Shreya Chatterjee",
    person1_designation: "Editor-in-Chief",
    person1_img: "/img/CommitteePanel/Shreya_Chatterjee_IP.jpg",
    person2: "",
    person2_designation: "",
    person2_img: "",
  },
];
