const senior_Council = [
  {
    name: "Vaibhav Gupta",
    category: "Sc",
    position: "Co-Director Of Technical Affairs",
    image: "/img/SC/Vaibhav Gupta (Director of Technical Affairs).webp",
    linkedin: "https://www.linkedin.com/in/zostera/",
  },
  {
    name: "Varun Negi",
    category: "Sc",
    position: "Co-Director Of Technical Affairs",
    // image: "/img/memberimg.png",
    linkedin: "https://www.linkedin.com/in/varun-negi-93b827223",
  },
  {
    name: "Arin Singhal",
    category: "Sc",
    position: "Director Of Administrative Affairs",
    image: "/img/SC/Arin Singhal (Director of Administration Affairs).png",
    linkedin: "https://www.linkedin.com/in/arinsinghal",
  },

  {
    name: "Hemabh Gupta",
    category: "Sc",
    position: "Director Of MUN ",
    image: "/img/SC/Hemabh Gupta(Director, MUN).png",
    linkedin: "https://www.linkedin.com/in/hemabh-gupta-054189224",
  },
  {
    name: " Sushant Nagi",
    category: "Sc",
    position: "Director Of Debating",
    image: "/img/SC/Sushant Nagi (Director of Debating).png",
    linkedin: "https://www.linkedin.com/in/sushant-nagi-15a1a623b/",
  },
  {
    name: " Vaibhav Kumar",
    category: "Sc",
    position: "Director Of Resarch & Policy ",
    image: "/img/SC/Vaibhav Kumar (Director of Research & Policy).png",
    linkedin: "https://www.linkedin.com/in/vaibhav-kumar-3ab66922b",
  },
  {
    name: "Divyam Goel ",
    category: "Sc",
    position: "Director Of Internal Affairs",
    image: "/img/SC/Divyam Goel (Director of Internal Affairs).png",
    linkedin: "https://www.linkedin.com/in/divyam-goel-0a42a722a",
  },
  {
    name: "Dhruv Rustagi",
    category: "Sc",
    position: "Director Of Publicity ",
    // image: "/img/memberimg.png",
    linkedin: "https://www.linkedin.com/in/dhruv-rustagi-05a8a5229/",
  },
  {
    name: " Adarsh Tiwari ",
    category: "Sc",
    position: "Director Of PR ",
    image: "/img/SC/Adarsh Tiwari.webp",
    linkedin: "http://www.linkedin.com/in/adarsh-tiwari04",
  },
  {
    name: "Akshat",
    category: "Sc",
    position: "Director Of Finace & Corporate ",
    image: "/img/SC/Akshat Agarwal (Director of Finance & Corporate).png",
    linkedin: "https://www.linkedin.com/in/akshatagrawal1717",
  },
  {
    name: "Ansh Bhatia",
    category: "Sc",
    position: " Deputy Director Of Finace & Corporate",
    image: "/img/SC/Ansh Bhatia (Deputy Director of Finance & Corporate).png",
    linkedin: "https://www.linkedin.com/in/ansh-bhatia-463062245",
  },
  {
    name: "Shivam Garg",
    category: "Sc",
    position: "Director Of Operations",
    image: "/img/SC/Shivam Garg (Director of Operations).png",
    linkedin: "http://linkedin.com/in/shivam-garg-25567318b",
  },
  {
    name: "Arnav Deep",
    category: "Sc",
    position: "Director Of Social & Outreach ",
    image: "/img/SC/Arnav Deep (Director of Social & Outreach).png",
    linkedin: "https://in.linkedin.com/in/arnav-deep-55559b206",
  },
  {
    name: "Prathamesh",
    category: "Sc",
    position: "Director Of Design",
    image: "/img/SC/Prathamesh.webp",
    linkedin: "https://www.linkedin.com/in/png03",
  },
  {
    name: "Riya",
    category: "Sc",
    position: "Deputy Director Of Design ",
    image: "/img/SC/Riya (Deputy Director of Design).png",
    linkedin: "https://www.linkedin.com/in/riya-%E2%80%8E-099b95244/",
  },
  {
    name: "Mahatva",
    category: "Sc",
    position: "Deputy Director Of Design",
    image: "/img/SC/Mahatva Anand (Deputy Director OF Design).png",
    // linkedin: "",
  },
  {
    name: "Sanskar Srivastava",
    category: "Sc",
    position: "Director Of Videography",
    image: "/img/SC/Sanskar Srivastava (Director of Videography).png",
    linkedin: "https://www.linkedin.com/in/sanskar-srivastava-234087217",
  },
  {
    name: "Pari",
    category: "Sc",
    position: "Deputy Director Of photography",
    image: "/img/SC/Pari jain ( Director of photography )-modified.png",
    linkedin: "https://www.linkedin.com/in/pari-jain-15305a246",
  },
  {
    name: "Vidushi Saxena",
    category: "Sc",
    position: "Director Of Content & Creation",
    image: "/img/SC/Vidhushi Saxena (Director of Content & Creation).png",
    linkedin: "https://www.linkedin.com/in/vidusi-saxena-004776231",
  },
  {
    name: "Ishank Dabas",
    category: "Sc",
    position: "Director of Logistics",
    image: "/img/SC/ishank dabas.jpg",
    linkedin: "https://www.linkedin.com/in/ishankdabas?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    name: "Mohit",
    category: "Sc",
    position: "Co-Director Of Technical Affairs",
    // image: "/img/memberimg.png",
    linkedin: "https://www.linkedin.com/in/mohit-singh-rajput-823829244",
  },
];

const junior_Council = [
  {
    name: "Rahul Shrama",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Rahul Sharma (Jc).webp",
    linkedin: "https://www.linkedin.com/in/rahul-sharma-a21916226",
  },
  {
    name: "Chaitanya Roy",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Chaitanya Roy (Jc).png",
    linkedin: "https://www.linkedin.com/in/chaitanya-roy-a8b756257",
  },
  {
    name: "Mohit Daber",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Mohit Daber (Jc).png",
    linkedin: "https://www.linkedin.com/in/mohit-daber-980841259",
  },
  {
    name: "Ayush Srivastav",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Ayush Srivastav (Jc).png",
    linkedin: "https://www.linkedin.com/in/ayush-srivastav-863759264/",
  },
  {
    name: "Gaurav Kapoor",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Gaurav Kapoor (Jc).png",
    linkedin: "https://www.linkedin.com/in/gaurav-kapoor-450832261",
  },
  {
    name: "Takshil Aggarwal",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Takshil Aggarwal (Jc).png",
    linkedin: "https://www.linkedin.com/in/takshil-aggarwal-254a07259",
  },
  {
    name: "Aditya Jha",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Aditya Jha (Jc).png",
    // linkedin: "",
  },
  {
    name: "Prashant Kaushik",
    category: "JC",
    position: "Junior Council",
    // image: "/img/memberimg.png",
    linkedin: "https://www.linkedin.com/in/prashant-kaushik-55a6a1256",
  },
  {
    name: "Sakshya singh",
    category: "JC",
    position: "Junior Council",
    // image: "/img/memberimg.png",
    linkedin: "https://www.linkedin.com/in/sakshya-singh-78b0a2144",
  },
  {
    name: "Shiwani Gupta",
    category: "JC",
    position: "Junior Council",
    // image: "/img/memberimg.png",
    linkedin: "https://www.linkedin.com/in/shiwani-gupta-2969b7248",
  },
  {
    name: "Nishit jain",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Nishit Jain (Jc).png",
    linkedin: "https://www.linkedin.com/in/nishit-jain-338472230/",
  },
  {
    name: "Evam Bansal",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Evam Bansal (Jc).png",
    linkedin: "https://www.linkedin.com/in/evam-bansal-176211183",
  },
  {
    name: "Pranav Gupta",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Pranav Gupta (Jc).png",
    linkedin: "https://www.linkedin.com/in/-pranav-gupta",
  },
  {
    name: "Tushit Kapoor",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Tushit Kapur (Jc).png",
    linkedin: "https://www.linkedin.com/in/tushit-kapur-a5b85b261/",
  },
  {
    name: "Rachit Singhal",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Rachit Singhal (Jc).png",
    linkedin: "https://www.linkedin.com/in/rachit-singhal-88a2971bb",
  },
  {
    name: "Ritika",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Ritika (Jc).webp",
    linkedin: "https://www.linkedin.com/in/ritika-mehar-13b59725b",
  },
  {
    name: "Shambhavi",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Shambhavi.png",
    linkedin: "https://www.linkedin.com/in/shambhavi-singh-3b1878290/",
  },
  {
    name: "parv Gupta",
    category: "JC",
    position: "Junior Council",
    // image: "/img/memberimg.png",
    // linkedin: "",
  },
  {
    name: "Khyati Tuli",
    category: "JC",
    position: "Junior Council",
    // image: "/img/memberimg.png",
    linkedin: "https://www.linkedin.com/in/khyati-tuli-688900227/",
  },
  {
    name: "Dev Adlakha",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/DEV ADLAKHA.png",
    linkedin: "https://www.linkedin.com/in/dev-adlakha-b692a6247/",
  },
  {
    name: "Uma Shankar",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Uma Shankar (Jc).png",
    linkedin: "https://www.linkedin.com/in/uma-shankar-96ab31229",
  },
  {
    name: "Akshit Mittal",
    category: "JC",
    position: "Junior Council",
    image: "/img/JC/Akshit Mittal (Jc).png",
    linkedin: "https://www.linkedin.com/in/akshit-mittal-70aa17256/",
  },
];

const east_Campus = [
  {
    name: "Priya Goyal",
    category: "Sc",
    position: "President",
    campus: "EAST CAMPUS",
    image: "/img/EC/Priya Goyal (President East Campus).png",
    linkedin: "https://www.linkedin.com/in/priya-goyal-975573237",
  },
  {
    name: "Mehak Shore",
    category: "Sc",
    position: "Vice-President",
    campus: "EAST CAMPUS",
    image: "/img/EC/Mehak Shore (VP East Campus).png",
    linkedin: "https://www.linkedin.com/in/mehak-shore-019690221/",
  },
  {
    name: "Shivi Sud",
    category: "Sc",
    position: "Vice-President",
    campus: "EAST CAMPUS",
    image: "/img/EC/Shivi Sud(vice president East Campus).png",
    linkedin: "https://www.linkedin.com/in/shivi-sud-70b44826b/",
  },
  {
    name: "Sonal Mohakud",
    category: "Sc",
    position: "Secretary",
    campus: "EAST CAMPUS",
    image: "/img/EC/Sonal (Secretary East Campus).png",
    linkedin: "https://www.linkedin.com/in/sonal-mohakud-22267a213/",
  },
  {
    name: "Ayushi Nasa",
    category: "Sc",
    position: "Treasurer",
    campus: "EAST CAMPUS",
    image: "/img/EC/Ayushi Nasa(Treasurer East campus).png",
    linkedin: "https://www.linkedin.com/in/ayushi-nasa-b2703324a",
  },
  {
    name: "Akriti Kumari",
    category: "Sc",
    position: "Corporate Head",
    campus: "EAST CAMPUS",
    image: "/img/EC/Akriti Kumari (Corporate Head East Campus).png",
    linkedin: "https://www.linkedin.com/in/akriti-kumari-a08013244",
  },
  {
    name: "Avril Sehgal",
    category: "Sc",
    position: "Quiz Head",
    campus: "EAST CAMPUS",
    image: "/img/EC/Avril Sehgal (Quiz Head East Campus).png",
    linkedin: "https://www.linkedin.com/in/avril-sehgal-a7938b264",
  },
  {
    name: "Mahi Tripathi",
    category: "Sc",
    position: "Research Head",
    campus: "EAST CAMPUS",
    image: "/img/EC/Mahi Tripathi (Research Head East Campus).png",
    linkedin: "https://www.linkedin.com/in/mahi-tripathi-2516001b7/",
  },
  {
    name: "Bhoomika Jain",
    category: "Sc",
    position: "PR Head",
    campus: "EAST CAMPUS",
    image: "/img/EC/Bhoomika (PR Head East Campus).png",
    linkedin: "https://www.linkedin.com/in/mahi-tripathi-2516001b7/",
  },
  {
    name: "Kashish Gupta",
    category: "Sc",
    position: "Debate & MUN Head",
    campus: "EAST CAMPUS",
    image: "/img/EC/Kashish Gupta (Debate and MUN Head East Campus).png",
    linkedin: "https://www.linkedin.com/in/kashishgupta0607/",
  },
];

const administrative_Council = [
  {
    name: "Rtanjay Shrivastava",
    category: "Ac",
    position: "President",
    image: "/img/AC/Rtanjay (President).png",
    linkedin: "https://www.linkedin.com/in/rtanjay-shrivastava-63b3b1202",
  },
  {
    name: "Ritika Rai",
    category: "Ac",
    position: "Vice-President",
    image: "/img/AC/Ritika_Rai(VP).png",
    linkedin: "https://www.linkedin.com/in/ritika-rai-1b8a3b20b/",
  },
  {
    name: "Tushar",
    category: "Ac",
    position: "Chief Advisor",
    image: "/img/AC/Tushar (Chief Advisor).png",
    linkedin: "https://www.linkedin.com/in/tushar-t-63a1b2192",
  },
];

export { senior_Council, junior_Council, east_Campus, administrative_Council };